# Generated by Django 6.0 on 2025-12-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_category_order_orderitem_product_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_type_name', models.CharField(max_length=255)),
            ],
        ),

        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('supplier_address', models.TextField()),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_website', models.URLField(blank=True, null=True)),
                ('supplier_social', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_detail', models.TextField()),
                ('footer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.footertype')),
            ],
        ),

    ]
