# Generated by Django 6.0 on 2025-12-15
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_banner"),
    ]

    operations = [
        # Align Order fields with the current model
        migrations.RenameField(
            model_name="order",
            old_name="order_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_status",
        ),
        migrations.AddField(
            model_name="order",
            name="order_code",
            field=models.CharField(
                blank=True, null=True, unique=True, max_length=50
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(max_length=100, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(max_length=20, default="COD"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(max_length=20, default="pending"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(max_length=20, default="pending"),
        ),
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(max_digits=12, decimal_places=2),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                related_name="orders",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                to="accounts.user",
            ),
        ),
        # Align OrderItem fields
        migrations.RenameField(
            model_name="orderitem",
            old_name="item_price",
            new_name="price",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=150, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(
                max_digits=12, decimal_places=2, null=True, blank=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                max_digits=12, decimal_places=2, null=True, blank=True
            ),
        ),
        # Add Payment model
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=20)),
                ("amount", models.DecimalField(max_digits=12, decimal_places=2)),
                (
                    "receipt_image",
                    models.ImageField(upload_to="payments/", blank=True, null=True),
                ),
                ("status", models.CharField(max_length=20, default="pending")),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.order",
                    ),
                ),
            ],
        ),
    ]

