# Generated by Django 6.0 on 2025-12-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KHR', 'KHR')], default='USD', max_length=3),
        ),
    ]
