# Generated by Django 6.0 on 2025-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(default='Admin', max_length=40)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
