# Generated by Django 6.0 on 2025-12-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_payment_created_at_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payway_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
