# Generated by Django 6.0 on 2025-12-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_product_payway_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("hot", "Hot"), ("discount", "Discount")],
                default="",
                max_length=20,
            ),
        ),
    ]
