"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-k^4i4!o0!4l8)lu6nzu8+w2*$@8oa-p8wn1!g!m@e%=f7^xu#0",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"


def _split_env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


ALLOWED_HOSTS = _split_env_list("ALLOWED_HOSTS", "*")


# Application definition

INSTALLED_APPS = [
    'jazzmin',         # must come before 'django.contrib.admin'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'accounts',
            # your custom app
]


JAZZMIN_SETTINGS = {
    "site_title": "My Project Admin",
    "site_header": "My Admin Dashboard",
    "welcome_sign": "Welcome to My Admin",
    "copyright": "My Company",
    "search_model": "auth.User",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
    }
}
JAZZMIN_SETTINGS = {
    "site_title": "My Store Admin",
    "site_header": "My Store Dashboard",
    "welcome_sign": "Welcome to My Product Store",
    "icons": {
        "core.Category": "fas fa-tags",
        "core.Product": "fas fa-boxes",
    },
}


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True").lower() == "true"

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = os.getenv("MEDIA_ROOT", str(BASE_DIR / "media"))
SERVE_MEDIA = os.getenv("SERVE_MEDIA", "False").lower() == "true"

# Ensure media directory exists when using a mounted volume.
try:
    os.makedirs(MEDIA_ROOT, exist_ok=True)
except OSError:
    # Skip if the volume is not mounted yet.
    pass


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.admin_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'
ASGI_APPLICATION = 'crm.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Phnom_Penh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = os.getenv(
    "STATICFILES_STORAGE",
    "whitenoise.storage.CompressedStaticFilesStorage",
)
WHITENOISE_USE_FINDERS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:64129",
    "http://localhost:65008",
]

CSRF_TRUSTED_ORIGINS = _split_env_list("CSRF_TRUSTED_ORIGINS")

_railway_public_domain = os.getenv("RAILWAY_PUBLIC_DOMAIN", "").strip()
if _railway_public_domain:
    CSRF_TRUSTED_ORIGINS.extend(
        [
            f"https://{_railway_public_domain}",
            f"http://{_railway_public_domain}",
        ]
    )

# --- Payment / Telegram integrations ---
PAYWAY_MERCHANT_ID = os.getenv("PAYWAY_MERCHANT_ID", "")
PAYWAY_API_KEY = os.getenv("PAYWAY_API_KEY", "")
PAYWAY_BASE_URL = os.getenv("PAYWAY_BASE_URL", "https://link.payway.com.kh")
PAYWAY_CHECKOUT_URL = os.getenv("PAYWAY_CHECKOUT_URL", PAYWAY_BASE_URL)
PAYWAY_SAMPLE_LINK = os.getenv(
    "PAYWAY_SAMPLE_LINK",
    "https://link.payway.com.kh/aba?id=BC9C1637D99A&dynamic=true&source_caller=sdk&pid=af_app_invites&link_action=abaqr&shortlink=qom57m9s&created_from_app=true&acc=007253721&af_siteid=968860649&userid=BC9C1637D99A&code=099743&c=abaqr&af_referrer_uid=1695695806092-3948219",
)
PAYMENT_QR_GENERATOR_URL = os.getenv(
    "PAYMENT_QR_GENERATOR_URL",
    "https://api.qrserver.com/v1/create-qr-code/?size=240x240&data={data}",
)
PAYWAY_RETURN_URL = os.getenv("PAYWAY_RETURN_URL", "")
PAYWAY_CALLBACK_URL = os.getenv(
    "PAYWAY_CALLBACK_URL", "https://example.com/api/payments/callback"
)
PAYWAY_CURRENCY = os.getenv("PAYWAY_CURRENCY", "USD")
PAYMENT_RECEIPT_MAX_MB = int(os.getenv("PAYMENT_RECEIPT_MAX_MB", "5"))
ABA_QR_CODE_URL = os.getenv("ABA_QR_CODE_URL", f"{MEDIA_URL}qr/aba.jpg")
AC_QR_CODE_URL = os.getenv("AC_QR_CODE_URL", f"{MEDIA_URL}qr/ac.jpg")
PAYMENT_QR_CODE_URLS = {
    "ABA_QR": ABA_QR_CODE_URL,
    "AC_QR": AC_QR_CODE_URL,
}

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")


 
